version: '3.9'
services:
 builder:
   build: .
   # restart: no
   volumes:
     - /home/clay/ros:/home/ros
     - /home/clay/arachne:/ros2
   #devices:
    # - /dev/ttyUSB0:/dev/ttyUSB0
   command: >
       bash -c "apt update && 
       apt install -y python3-colcon-common-extensions && 
       cd ros2/ros2_ws && 
       colcon build && 
       source install/setup.sh &&
       colcon test"
   #environment:
     #- ROS_DOMAIN_ID=737
 talker:
   build: .
   # restart: no
   volumes:
     - /home/clay/ros:/home/ros
     - /home/clay/arachne:/ros2
   #devices:
    # - /dev/ttyUSB0:/dev/ttyUSB0
   command: >
       bash -c "cd ros2/ros2_ws &&  
       source install/setup.sh && 
       source /ros_entrypoint.sh &&
       ros2 run testcomms talker"
 pub:
   build: .
   # restart: no
   volumes:
     - /home/clay/ros:/home/ros
     - /home/clay/arachne:/ros2
   #devices:
    # - /dev/ttyUSB0:/dev/ttyUSB0
   command: >
       bash -c "cd ros2/ros2_ws &&  
       source install/setup.sh && 
       source /ros_entrypoint.sh &&
       ros2 run testcomms pub"
 ros-shell:
   build: .
   # restart: no
   ports: 
     - "3332:3332"
   volumes:
     - /home/clay/ros:/home/ros
     - /home/clay/arachne:/ros2
   #devices:
     # - /dev/ttyUSB0:/dev/ttyUSB0
   tty: true
   command: >
       bash -c "cd ros2/ros2_ws &&  
       source install/setup.sh && 
       source /ros_entrypoint.sh &&
       tail -f /dev/null"